import os
import tempfile

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors


def generate_report(data: dict) -> str:
    """
    Generate a PDF from analysis data.
    Returns the path to a unique temp file. Caller must delete it after serving.
    """

    tmp = tempfile.NamedTemporaryFile(
        suffix=".pdf", delete=False, prefix="phishguard_"
    )
    tmp.close()

    pdf = SimpleDocTemplate(tmp.name)

    styles = getSampleStyleSheet()

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
        alignment=1,  # centre
    )

    story = []

    # ----------------------------
    # Title
    # ----------------------------

    story.append(Paragraph("<b>PhishGuard AI — Threat Analysis Report</b>", styles["Heading1"]))
    story.append(Spacer(1, 0.4 * cm))

    # ----------------------------
    # Meta
    # ----------------------------

    story.append(Paragraph(f"<b>Timestamp:</b> {data['timestamp']}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Analysis Source:</b> {data['source']}", styles["BodyText"]))
    story.append(Spacer(1, 0.4 * cm))

    # ----------------------------
    # Result
    # ----------------------------

    story.append(Paragraph(f"<b>Risk:</b> {data['risk']}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Confidence:</b> {data['confidence']}", styles["BodyText"]))
    story.append(Spacer(1, 0.3 * cm))

    # ----------------------------
    # Reasons
    # ----------------------------

    story.append(Paragraph("<b>Reasons:</b>", styles["Heading2"]))

    for reason in data["reason"]:
        story.append(Paragraph("• " + reason, styles["BodyText"]))

    story.append(Spacer(1, 0.3 * cm))

    # ----------------------------
    # Recommendation
    # ----------------------------

    story.append(Paragraph("<b>Recommendation:</b>", styles["Heading2"]))
    story.append(Paragraph(data["recommendation"], styles["BodyText"]))
    story.append(Spacer(1, 0.4 * cm))

    # ----------------------------
    # Original Message
    # ----------------------------

    story.append(Paragraph("<b>Original Message:</b>", styles["Heading2"]))
    story.append(Paragraph(data["message"], styles["BodyText"]))
    story.append(Spacer(1, 0.8 * cm))

    # ----------------------------
    # Footer
    # ----------------------------

    story.append(Paragraph("Generated by PhishGuard AI", footer_style))
    story.append(Paragraph("AI-powered Phishing Detection System", footer_style))
    story.append(Paragraph("IBM SkillsBuild Internship Project", footer_style))

    pdf.build(story)

    return tmp.name
